<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Welcome!</title>
  <meta charset="UTF-8">
	<title>Portfolio</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  	<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
	<link rel="stylesheet" type="text/css" href="/css/welcome.css" /> 
</head>

<body>

<!-- header -->
<div class="wrapper" id="welcomepage">
	<header class="header">
		<div class="logo">
			<br>
			<img src="https://media.istockphoto.com/photos/open-iron-gate-picture-id495958942?k=6&m=495958942&s=612x612&w=0&h=j5B-HnaO6TFVAB3n0HHBtPG2LvOuo_iNXC_vqcMmzqY=">
		</div>
	</header>
<!-- welcome page -->
	<section class="welcomepage">
		<div class="welcome">
			<h1>Welcome</h1>
		</div>
	</section>
<!-- nav -->
	<nav class="navigation sticky">
		<ul class="menu">
			<li><a href="#welcomepage"></a></li>
			<li><a href="/login">LOGIN</a></li>
			<li><a href="/users">SIGNUP</a></li>
			<li><a href="/gates">GATE</a></li>
			<li><a href="#contactpage"></a></li>
		</ul>
	</nav>
</div>

</body>

</html>
